baseURL: "https://547Final.com/" 
languageCode: "en-us"
title: "CISA Vulnerabilities"
theme: "ananke"

params:
  author: "Group 3"
  description: "A website built with Hugo and the Ananke theme."
  githubURL: "https://github.com/dianaltl"
  custom_css: ["css/custom.css"]
  
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 2
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 3
      children:
        - identifier: "post1"
          name: "Post 1"
          url: "/posts/post1/"
          weight: 1
        - identifier: "post2"
          name: "Post 2"
          url: "/posts/post2/"
          weight: 2
